# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: rgba(30, 30, 30, 0.1);\n"
"    color: white;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical,\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgba(30, 30, 30, 0);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgba(139, 139, 139, 0);\n"
"    min-height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:vertical:pressed,\n"
"QScrollBar::handle:horizontal:hover,\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgba(149, 149, 149, 0);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical, \n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    border-color: rgba(48, 48, 48, 0.5);\n"
"    background-color: rgba(44, 45, 46, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    border-width: 2px;\n"
"    background-color: rgba(50, 50, 50, 0.7);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(38, 39, 40, 0.7);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(67, 67, 67, 0.7);\n"
"    border-color: rgba(0, 0, 0, 0.7);\n"
"}\n"
"\n"
"\n"
"QLineEdit, QTextBrowser, QPlainTextEdit, QTextEdit {\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-color: rgba(48, 48, 48);\n"
"    background-color: rgba(36, 36, 36, 0);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QListWidget {\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-color: rgba(48, 48, 48);\n"
"    padding: 10px;\n"
"    background-color: rgba(100, 100, 100, 0);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QListWidget:item {\n"
"    background-color: rgba(36, 36, 36, 0);\n"
"    selection-color: white;\n"
"}\n"
"QListWidget:item:hover {\n"
"    background-color: rgba(50, 50, 50, 0);\n"
"}\n"
"QListWidget:item:selected {\n"
"    background-color: rgba(119, 119, 119, 1);\n"
"}\n"
"\n"
"\n"
"QComboBox\n"
"{\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    border-color: rgba(48, 48, 48);\n"
"    background-color: rgba(44, 45, 46, 0);\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: rgba(67, 67, 67, 0);\n"
"    color: #656565;\n"
"    border-color: rgba(67, 67, 67);\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: rgba(50, 50, 50, 0);\n"
"}\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: rgba(67, 67, 67, 0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: rgba(67, 67, 67, 0);\n"
"    color: #ffffff;\n"
"    selection-background-color: rgba(119, 119, 119, 0);\n"
"    selection-color: white;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 6px; \n"
"}\n"
"\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    background-color: rgba(44, 45, 46, 0);\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: rgba(48, 48, 48);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: rgba(101, 101, 101, 0);\n"
"    color: #656565;\n"
"}\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: rgba(160, 160, 160, 0);\n"
"    color: #ffffff;\n"
"    border: 3px solid;\n"
"    border-radius: 15px;\n"
"    border-color: rgba(28, 28, 28);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: rgba(38, 39, 40, 0);\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: rgba(48, 48, 48);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: rgba(64, 64, 64, 0);\n"
"    color: #656565;\n"
"}\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: rgba(38, 38, 38, 0);\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: rgba(50, 50, 50, 0);\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-color: rgba(48, 48, 48);\n"
"    background-color: rgba(36, 36, 36, 0);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QSpinBox::up-button {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"QSpinBox::down-button {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: rgba(48, 48, 48, 0);\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.page_text.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.page_text.setObjectName("page_text")
        self.verticalLayout.addWidget(self.page_text)
        self.index_widget = QtWidgets.QWidget(self.centralwidget)
        self.index_widget.setObjectName("index_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.index_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtWidgets.QPushButton(self.index_widget)
        self.back_button.setMinimumSize(QtCore.QSize(64, 64))
        self.back_button.setMaximumSize(QtCore.QSize(64, 64))
        self.back_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
        self.back_button.setIconSize(QtCore.QSize(40, 40))
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.page_index = QtWidgets.QLineEdit(self.index_widget)
        self.page_index.setMinimumSize(QtCore.QSize(0, 64))
        self.page_index.setMaxLength(2932)
        self.page_index.setObjectName("page_index")
        self.horizontalLayout.addWidget(self.page_index)
        self.next_button = QtWidgets.QPushButton(self.index_widget)
        self.next_button.setMinimumSize(QtCore.QSize(64, 64))
        self.next_button.setMaximumSize(QtCore.QSize(64, 64))
        self.next_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon1)
        self.next_button.setIconSize(QtCore.QSize(40, 40))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.verticalLayout.addWidget(self.index_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ConsistentLibraryOfBabel"))
import ui.images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
